import apiClient from './client';
import type { VerificationReport, Application } from '../types';
import { mockApplications } from '../mock/data';

const useMock = import.meta.env.VITE_USE_MOCK === 'true';

export async function getReport(applicationId: string): Promise<VerificationReport> {
  if (useMock) {
    await delay(700);
    const app = mockApplications.find(a => a.application_id === applicationId);
    if (!app) throw new Error(`Application ${applicationId} not found`);
    return buildReportFromApp(app);
  }

  const response = await apiClient.get<VerificationReport>(
    `/applications/${applicationId}/report`
  );
  return response.data;
}

export async function downloadReport(applicationId: string): Promise<void> {
  if (useMock) {
    // In mock mode, generate a simple text-based report download
    const app = mockApplications.find(a => a.application_id === applicationId);
    if (!app) throw new Error(`Application ${applicationId} not found`);

    const report = buildReportFromApp(app);
    const text = generateReportText(report);
    const blob = new Blob([text], { type: 'text/plain' });
    triggerDownload(blob, `LoanIQ_Report_${applicationId}.txt`);
    return;
  }

  const response = await apiClient.get(`/applications/${applicationId}/report/download`, {
    responseType: 'blob',
  });

  const headerVal = response.headers['content-type'];
  const contentType = typeof headerVal === 'string' ? headerVal : 'application/pdf';
  const ext = contentType.includes('pdf') ? 'pdf' : 'json';
  const blob = new Blob([response.data], { type: contentType });
  triggerDownload(blob, `LoanIQ_Report_${applicationId}.${ext}`);
}

function triggerDownload(blob: Blob, filename: string) {
  const url = window.URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  window.URL.revokeObjectURL(url);
}

function buildReportFromApp(app: Application): VerificationReport {
  return {
    application_id: app.application_id,
    applicant_name: app.applicant_name,
    generated_at: new Date().toISOString(),
    documents_reviewed: app.documents.filter(d => d.status === 'completed').length,
    risk_score: app.risk.score,
    risk_level: app.risk.level,
    flags: app.risk.flags,
    verification_results: [...app.verification.matches, ...app.verification.mismatches],
    missing_documents: app.verification.missing_documents,
    recommendation: app.recommendation,
  };
}

function generateReportText(report: VerificationReport): string {
  const lines: string[] = [
    '═══════════════════════════════════════════════════════',
    '                    LoanIQ',
    '            Loan Verification Report',
    '═══════════════════════════════════════════════════════',
    '',
    `Application ID:     ${report.application_id}`,
    `Applicant:          ${report.applicant_name}`,
    `Generated:          ${new Date(report.generated_at).toLocaleString()}`,
    `Documents Reviewed: ${report.documents_reviewed}`,
    '',
    '───────────────────────────────────────────────────────',
    '  RISK ASSESSMENT',
    '───────────────────────────────────────────────────────',
    '',
    `Risk Score:         ${report.risk_score}/100`,
    `Risk Level:         ${report.risk_level}`,
    '',
  ];

  if (report.flags.length > 0) {
    lines.push('───────────────────────────────────────────────────────');
    lines.push('  FLAGS & ISSUES');
    lines.push('───────────────────────────────────────────────────────');
    lines.push('');
    report.flags.forEach(flag => {
      lines.push(`  [${flag.severity}] ${flag.reason}`);
      lines.push(`  ${flag.details}`);
      lines.push('');
    });
  }

  if (report.missing_documents.length > 0) {
    lines.push('───────────────────────────────────────────────────────');
    lines.push('  MISSING DOCUMENTS');
    lines.push('───────────────────────────────────────────────────────');
    lines.push('');
    report.missing_documents.forEach(doc => {
      lines.push(`  • ${doc}`);
    });
    lines.push('');
  }

  lines.push('───────────────────────────────────────────────────────');
  lines.push('  RECOMMENDATION');
  lines.push('───────────────────────────────────────────────────────');
  lines.push('');
  lines.push(`  ${report.recommendation.replace(/_/g, ' ')}`);
  lines.push('');
  lines.push('═══════════════════════════════════════════════════════');
  lines.push('  This report is generated by LoanIQ AI system.');
  lines.push('  Final lending decisions are made by authorized officers.');
  lines.push('═══════════════════════════════════════════════════════');

  return lines.join('\n');
}

function delay(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}
