import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Download, FileText, CheckCircle, AlertTriangle, AlertCircle, Info } from 'lucide-react';
import { useState, useEffect } from 'react';
import { Topbar } from '../components/layout/Topbar';
import { Spinner } from '../components/ui/Spinner';
import { ErrorState } from '../components/ui/ErrorState';
import { RiskBadge } from '../components/applications/StatusBadge';
import { Button } from '../components/ui/Button';
import { getReport, downloadReport } from '../api/reports';
import { getRiskColor, formatDateTime, classNames } from '../lib/utils';
import type { VerificationReport } from '../types';

export function Report() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [report, setReport] = useState<VerificationReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    if (!id) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    getReport(id)
      .then((data) => { if (!cancelled) setReport(data); })
      .catch((err) => { if (!cancelled) setError(err.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [id]);

  const handleDownload = async () => {
    if (!id) return;
    setDownloading(true);
    try { await downloadReport(id); } catch { /* silent */ } finally { setDownloading(false); }
  };

  const riskColors = report ? getRiskColor(report.risk_level) : null;

  return (
    <div className="min-h-screen flex flex-col" style={{ background: '#0A0A0A' }}>
      <Topbar
        title="Verification Report"
        subtitle={`Audit-ready summary for Application ID: ${id || 'N/A'}`}
      />

      <main className="flex-1 p-6 max-w-5xl w-full mx-auto space-y-6 animate-fade-in">
        {/* Back nav */}
        <button
          onClick={() => navigate(id ? `/applications/${id}` : '/reports')}
          className="inline-flex items-center gap-1.5 text-xs font-medium transition-colors hover:text-charcoal"
          style={{ color: '#555555' }}
        >
          <ArrowLeft className="h-4 w-4" /> Back
        </button>

        {loading ? (
          <div className="py-20 flex justify-center">
            <Spinner size="lg" text="Generating report..." />
          </div>
        ) : error ? (
          <ErrorState title="Failed to load report" message={error} onRetry={() => window.location.reload()} />
        ) : !report ? (
          <ErrorState title="Report not found" message="No report found for this application." />
        ) : (
          <div className="space-y-4">
            {/* Report Header Card */}
            <div
              className="rounded-xl overflow-hidden"
              style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.06)' }}
            >
              {/* Header */}
              <div className="px-6 py-5 flex items-start justify-between" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                <div className="flex items-center gap-3">
                  <div
                    className="w-10 h-10 rounded-lg flex items-center justify-center"
                    style={{ background: 'rgba(170,255,0,0.1)', border: '1px solid rgba(170,255,0,0.15)' }}
                  >
                    <FileText className="h-5 w-5" style={{ color: '#AAFF00' }} />
                  </div>
                  <div>
                    <h2 className="text-xl font-semibold" style={{ color: '#F0F0F0' }}>
                      Loan Verification Report
                    </h2>
                    <p className="text-sm" style={{ color: '#555555' }}>Generated by LoanPilot AI</p>
                  </div>
                </div>
                <Button onClick={handleDownload} loading={downloading} variant="secondary" size="sm" icon={Download}>
                  Download PDF
                </Button>
              </div>

              {/* Meta grid */}
              <div
                className="px-6 py-4 grid grid-cols-2 md:grid-cols-4 gap-6"
                style={{ background: 'rgba(255,255,255,0.02)' }}
              >
                {[
                  { label: 'Application ID', value: report.application_id },
                  { label: 'Applicant', value: report.applicant_name },
                  { label: 'Documents Reviewed', value: String(report.documents_reviewed) },
                  { label: 'Generated', value: formatDateTime(report.generated_at) },
                ].map(({ label, value }) => (
                  <div key={label}>
                    <p className="text-xs" style={{ color: '#444444' }}>{label}</p>
                    <p className="text-sm font-medium mt-0.5" style={{ color: '#F0F0F0' }}>{value}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Risk Assessment */}
            <div
              className="rounded-xl p-6"
              style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.06)' }}
            >
              <h3 className="text-base font-semibold mb-4" style={{ color: '#F0F0F0' }}>Risk Assessment</h3>
              <div className="flex items-center gap-8">
                <div>
                  <p className="text-xs mb-1" style={{ color: '#444444' }}>Risk Score</p>
                  <div className="flex items-baseline gap-1">
                    <span className="text-4xl font-bold tabular-nums" style={{ color: '#F0F0F0' }}>
                      {report.risk_score}
                    </span>
                    <span className="text-sm" style={{ color: '#555555' }}>/100</span>
                  </div>
                </div>
                <div className="w-px h-14" style={{ background: 'rgba(255,255,255,0.06)' }} />
                <div>
                  <p className="text-xs mb-2" style={{ color: '#444444' }}>Risk Level</p>
                  <RiskBadge level={report.risk_level} />
                </div>
              </div>
            </div>

            {/* Flags */}
            {report.flags.length > 0 && (
              <div
                className="rounded-xl p-6"
                style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.06)' }}
              >
                <h3 className="text-base font-semibold mb-4" style={{ color: '#F0F0F0' }}>Flags & Issues</h3>
                <div className="space-y-3">
                  {report.flags.map((flag) => {
                    const fc = getRiskColor(flag.severity);
                    return (
                      <div
                        key={flag.id}
                        className={classNames('flex items-start gap-3 p-3 rounded-lg border', fc.bg, fc.border)}
                      >
                        <span className={classNames('mt-0.5 flex-shrink-0', fc.text)}>
                          {flag.severity === 'HIGH' ? <AlertCircle className="h-4 w-4" /> :
                           flag.severity === 'MEDIUM' ? <AlertTriangle className="h-4 w-4" /> :
                           flag.severity === 'PASS' ? <CheckCircle className="h-4 w-4" /> :
                           <Info className="h-4 w-4" />}
                        </span>
                        <div>
                          <p className="text-sm font-medium" style={{ color: '#F0F0F0' }}>{flag.reason}</p>
                          <p className="text-xs mt-0.5" style={{ color: '#A0A0A0' }}>{flag.details}</p>
                        </div>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Verification Results */}
            {report.verification_results.length > 0 && (
              <div
                className="rounded-xl overflow-hidden"
                style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.06)' }}
              >
                <div className="px-6 py-4" style={{ borderBottom: '1px solid rgba(255,255,255,0.06)' }}>
                  <h3 className="text-base font-semibold" style={{ color: '#F0F0F0' }}>Verification Results</h3>
                </div>
                <table className="w-full text-sm">
                  <thead>
                    <tr style={{ background: 'rgba(255,255,255,0.02)', borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                      <th className="text-left py-2.5 px-6 text-xs font-semibold uppercase tracking-wider" style={{ color: '#444444' }}>Field</th>
                      <th className="text-center py-2.5 px-6 text-xs font-semibold uppercase tracking-wider" style={{ color: '#444444' }}>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.verification_results.map((r, i) => {
                      const isPass = r.status === 'PASS';
                      return (
                        <tr key={i} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                          <td className="py-3 px-6 font-medium" style={{ color: '#F0F0F0' }}>{r.field_name}</td>
                          <td className="py-3 px-6 text-center">
                            <span
                              className="inline-flex items-center px-2.5 py-0.5 text-xs font-semibold rounded-full border"
                              style={isPass
                                ? { color: '#30D158', background: 'rgba(48,209,88,0.1)', borderColor: 'rgba(48,209,88,0.2)' }
                                : { color: '#FF453A', background: 'rgba(255,69,58,0.1)', borderColor: 'rgba(255,69,58,0.2)' }
                              }
                            >
                              {r.status}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}

            {/* Missing Documents */}
            {report.missing_documents.length > 0 && (
              <div
                className="rounded-xl p-6"
                style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.06)' }}
              >
                <h3 className="text-base font-semibold mb-3" style={{ color: '#F0F0F0' }}>Missing Documents</h3>
                <div className="space-y-2">
                  {report.missing_documents.map((doc) => (
                    <div key={doc} className="flex items-center gap-2 text-sm" style={{ color: '#A0A0A0' }}>
                      <AlertTriangle className="h-4 w-4 flex-shrink-0" style={{ color: '#FFB340' }} />
                      {doc}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Recommendation */}
            <div
              className="rounded-xl p-6"
              style={{ background: '#111111', border: '1px solid rgba(255,255,255,0.06)' }}
            >
              <h3 className="text-base font-semibold mb-3" style={{ color: '#F0F0F0' }}>Recommendation</h3>
              {riskColors && (
                <div className={classNames('flex items-center gap-3 p-4 rounded-lg border', riskColors.bg, riskColors.border)}>
                  <span className={classNames('flex-shrink-0', riskColors.text)}>
                    {report.recommendation === 'APPROVE' ? <CheckCircle className="h-5 w-5" /> :
                     report.recommendation === 'REJECT' ? <AlertCircle className="h-5 w-5" /> :
                     <AlertTriangle className="h-5 w-5" />}
                  </span>
                  <span className="text-sm font-semibold" style={{ color: '#F0F0F0' }}>
                    {report.recommendation.replace(/_/g, ' ')}
                  </span>
                </div>
              )}
              <p className="text-xs mt-3" style={{ color: '#444444' }}>
                This report is generated by LoanPilot AI. Final lending decisions are made by authorized loan officers.
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
