import { useState, useEffect } from 'react';
import { Download, FileText, CheckCircle, AlertTriangle, AlertCircle, Info } from 'lucide-react';
import type { VerificationReport } from '../../types';
import { getReport, downloadReport } from '../../api/reports';
import { getRiskColor, formatDateTime, classNames } from '../../lib/utils';
import { RiskBadge } from '../applications/StatusBadge';
import { Button } from '../ui/Button';
import { LoadingState } from '../ui/Spinner';
import { ErrorState } from '../ui/ErrorState';

interface ReportViewerProps {
  applicationId: string;
}

export function ReportViewer({ applicationId }: ReportViewerProps) {
  const [report, setReport] = useState<VerificationReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [downloading, setDownloading] = useState(false);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    setError(null);
    getReport(applicationId)
      .then((data) => { if (!cancelled) setReport(data); })
      .catch((err) => { if (!cancelled) setError(err.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [applicationId]);

  const handleDownload = async () => {
    setDownloading(true);
    try {
      await downloadReport(applicationId);
    } catch {
      // Download error — silently handled
    } finally {
      setDownloading(false);
    }
  };

  if (loading) return <LoadingState message="Generating report..." />;
  if (error) return <ErrorState message={error} onRetry={() => window.location.reload()} />;
  if (!report) return <ErrorState message="Report not found." />;

  const riskColors = getRiskColor(report.risk_level);

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Report Header */}
      <div className="bg-white border border-surface-300 rounded-lg shadow-card overflow-hidden">
        <div className="px-6 py-5 border-b border-surface-300">
          <div className="flex items-start justify-between">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary-50 flex items-center justify-center">
                <FileText className="h-5 w-5 text-primary-600" />
              </div>
              <div>
                <h2 className="text-xl font-semibold text-charcoal">Loan Verification Report</h2>
                <p className="text-sm text-charcoal-muted">Generated by LoanIQ</p>
              </div>
            </div>
            <Button onClick={handleDownload} loading={downloading} variant="secondary" size="sm">
              <Download className="h-4 w-4" />
              Download Report
            </Button>
          </div>
        </div>

        {/* Report Meta */}
        <div className="px-6 py-4 grid grid-cols-2 md:grid-cols-4 gap-4 bg-surface-50">
          <div>
            <p className="text-xs text-charcoal-muted">Application ID</p>
            <p className="text-sm font-medium text-charcoal mt-0.5">{report.application_id}</p>
          </div>
          <div>
            <p className="text-xs text-charcoal-muted">Applicant</p>
            <p className="text-sm font-medium text-charcoal mt-0.5">{report.applicant_name}</p>
          </div>
          <div>
            <p className="text-xs text-charcoal-muted">Documents Reviewed</p>
            <p className="text-sm font-medium text-charcoal mt-0.5">{report.documents_reviewed}</p>
          </div>
          <div>
            <p className="text-xs text-charcoal-muted">Generated</p>
            <p className="text-sm font-medium text-charcoal mt-0.5">{formatDateTime(report.generated_at)}</p>
          </div>
        </div>
      </div>

      {/* Risk Assessment */}
      <div className="bg-white border border-surface-300 rounded-lg shadow-card p-6">
        <h3 className="text-base font-semibold text-charcoal mb-4">Risk Assessment</h3>
        <div className="flex items-center gap-6">
          <div>
            <p className="text-xs text-charcoal-muted mb-1">Risk Score</p>
            <span className="text-4xl font-bold text-charcoal tabular-nums">{report.risk_score}</span>
            <span className="text-sm text-charcoal-muted">/100</span>
          </div>
          <div className="w-px h-16 bg-surface-300" />
          <div>
            <p className="text-xs text-charcoal-muted mb-1">Risk Level</p>
            <RiskBadge level={report.risk_level} />
          </div>
        </div>
      </div>

      {/* Flags */}
      {report.flags.length > 0 && (
        <div className="bg-white border border-surface-300 rounded-lg shadow-card p-6">
          <h3 className="text-base font-semibold text-charcoal mb-4">Flags & Issues</h3>
          <div className="space-y-3">
            {report.flags.map((flag) => {
              const fc = getRiskColor(flag.severity);
              return (
                <div key={flag.id} className={classNames('flex items-start gap-3 p-3 rounded-md border', fc.bg, fc.border)}>
                  <span className={classNames('mt-0.5', fc.text)}>
                    {flag.severity === 'HIGH' ? <AlertCircle className="h-4 w-4" /> :
                     flag.severity === 'MEDIUM' ? <AlertTriangle className="h-4 w-4" /> :
                     flag.severity === 'PASS' ? <CheckCircle className="h-4 w-4" /> :
                     <Info className="h-4 w-4" />}
                  </span>
                  <div>
                    <p className="text-sm font-medium text-charcoal">{flag.reason}</p>
                    <p className="text-xs text-charcoal-secondary mt-0.5">{flag.details}</p>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Verification Results */}
      {report.verification_results.length > 0 && (
        <div className="bg-white border border-surface-300 rounded-lg shadow-card overflow-hidden">
          <div className="px-6 py-4 border-b border-surface-300">
            <h3 className="text-base font-semibold text-charcoal">Verification Results</h3>
          </div>
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-surface-50 border-b border-surface-200">
                <th className="text-left py-2.5 px-6 font-medium text-charcoal-muted text-xs uppercase tracking-wider">Field</th>
                <th className="text-center py-2.5 px-6 font-medium text-charcoal-muted text-xs uppercase tracking-wider">Status</th>
              </tr>
            </thead>
            <tbody>
              {report.verification_results.map((r, i) => {
                const colors = r.status === 'PASS'
                  ? { text: 'text-risk-low', bg: 'bg-risk-low-bg', border: 'border-risk-low-border' }
                  : { text: 'text-risk-high', bg: 'bg-risk-high-bg', border: 'border-risk-high-border' };
                return (
                  <tr key={i} className="border-b border-surface-200 last:border-0">
                    <td className="py-3 px-6 font-medium text-charcoal">{r.field_name}</td>
                    <td className="py-3 px-6 text-center">
                      <span className={classNames('inline-flex items-center px-2 py-0.5 text-xs font-semibold rounded border', colors.text, colors.bg, colors.border)}>
                        {r.status}
                      </span>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      {/* Missing Documents */}
      {report.missing_documents.length > 0 && (
        <div className="bg-white border border-surface-300 rounded-lg shadow-card p-6">
          <h3 className="text-base font-semibold text-charcoal mb-3">Missing Documents</h3>
          <div className="space-y-2">
            {report.missing_documents.map((doc) => (
              <div key={doc} className="flex items-center gap-2 text-sm text-charcoal-secondary">
                <AlertTriangle className="h-4 w-4 text-risk-medium flex-shrink-0" />
                {doc}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Recommendation */}
      <div className="bg-white border border-surface-300 rounded-lg shadow-card p-6">
        <h3 className="text-base font-semibold text-charcoal mb-3">Recommendation</h3>
        <div className={classNames('flex items-center gap-3 p-4 rounded-md border', riskColors.bg, riskColors.border)}>
          <span className={riskColors.text}>
            {report.recommendation === 'APPROVE' ? <CheckCircle className="h-5 w-5" /> :
             report.recommendation === 'REJECT' ? <AlertCircle className="h-5 w-5" /> :
             <AlertTriangle className="h-5 w-5" />}
          </span>
          <span className="text-sm font-semibold text-charcoal">{report.recommendation.replace(/_/g, ' ')}</span>
        </div>
        <p className="text-xs text-charcoal-muted mt-3">
          This report is generated by LoanIQ AI system. Final lending decisions are made by authorized loan officers.
        </p>
      </div>
    </div>
  );
}
